"""
DeployBuddy RAG — Dynamic LLM Client
======================================
Satu interface untuk Ollama (lokal), OpenAI, Anthropic, dan Groq.
Semua dikontrol dari config.py atau environment variable.
"""

import json
import requests
from config import LLM_PROVIDER, LLM_CONFIGS, MAX_TOKENS, TEMPERATURE


class LLMClient:
    """
    Universal LLM client. Penggunaan:
        client = LLMClient()
        response = client.chat(system_prompt, user_message)
    """

    def __init__(self, provider: str = None):
        self.provider = provider or LLM_PROVIDER
        self.cfg = LLM_CONFIGS[self.provider]
        print(f"[LLMClient] Using provider: {self.provider} | model: {self.cfg['model']}")

    def chat(self, system_prompt: str, user_message: str) -> str:
        """Kirim pesan ke LLM, return response string."""
        if self.provider == "mock":
            return self._call_mock(system_prompt, user_message)
        elif self.provider == "ollama":
            return self._call_ollama(system_prompt, user_message)
        elif self.provider == "anthropic":
            return self._call_anthropic(system_prompt, user_message)
        else:
            # openai-compatible: openai, groq
            return self._call_openai_compat(system_prompt, user_message)

    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    # Mock (tests / local smoke checks)
    # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    def _call_mock(self, system_prompt: str, user_message: str) -> str:
        """Deterministic response for tests; does not call external services."""
        if "Deploy Code Generator" in system_prompt:
            return """
[FILE: deploy.py]
```python
\"\"\"Mock deployment script generated for local testing.\"\"\"

def main():
    print("Mock deploy only. Configure a real LLM provider for production output.")

if __name__ == "__main__":
    main()
```

[FILE: .env.example]
```env
# Fill provider credentials before real deployment.
DEPLOYBUDDY_MOCK=true
```

[FILE: DEPLOY_README.md]
```markdown
# Mock Deployment Guide

This file is generated by the mock LLM provider for smoke testing.
Use a real LLM provider to generate provider-specific deployment code.
```
"""

        stack_markers = []
        for marker in ("Next.js", "FastAPI", "PostgreSQL", "Docker", "Go", "Express"):
            if marker.lower() in user_message.lower():
                stack_markers.append(marker)
        detected = stack_markers or ["Repository stack not detected by mock"]

        return f"""
## Architecture Recommendation

Mock architecture recommendation generated for testing. Repository evidence detected:
{', '.join(detected)}.

## Provider Comparison

| Provider | Product | Region | Plan | Service Type | Est. Cost | Score |
|----------|---------|--------|------|-------------|-----------|-------|
| Vercel | App Hosting | ap-southeast-1 | hobby/pro | frontend | estimate required | 0.80 |
| Supabase | Postgres | ap-southeast-1 | free/pro | database | estimate required | 0.75 |

## Deployment Steps (Summary)

1. Build application using detected repository stack.
2. Provision managed database if required.
3. Deploy application to selected provider.

## Risks & Considerations

- Mock provider does not validate real provider pricing.

## Deployment Spec (JSON)

```json
{{
  "recommended_architecture": "container-or-serverless",
  "providers": [
    {{
      "provider": "Vercel",
      "product": "App Hosting",
      "region": "ap-southeast-1",
      "plan": "hobby/pro",
      "service_type": "frontend",
      "estimated_cost_usd": "estimate required",
      "role": "frontend"
    }},
    {{
      "provider": "Supabase",
      "product": "Postgres",
      "region": "ap-southeast-1",
      "plan": "free/pro",
      "service_type": "database",
      "estimated_cost_usd": "estimate required",
      "role": "database"
    }}
  ],
  "deployment_steps_summary": ["Build app", "Provision database", "Deploy services"],
  "risks": ["Mock response; use real provider for final recommendation"],
  "repository_analysis": {{
    "detected_stack": {json.dumps(detected)},
    "service_types": [],
    "databases": [],
    "important_files": []
  }}
}}
```
"""

    # ──────────────────────────────────────────
    # Ollama (local)
    # ──────────────────────────────────────────
    def _call_ollama(self, system_prompt: str, user_message: str) -> str:
        url = f"{self.cfg['base_url']}/api/chat"
        payload = {
            "model": self.cfg["model"],
            "stream": False,
            "options": {
                "temperature": TEMPERATURE,
                "num_predict": MAX_TOKENS,
            },
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_message},
            ],
        }
        resp = requests.post(url, json=payload, timeout=120)
        resp.raise_for_status()
        data = resp.json()
        return data["message"]["content"]

    # ──────────────────────────────────────────
    # OpenAI-compatible (OpenAI, Groq)
    # ──────────────────────────────────────────
    def _call_openai_compat(self, system_prompt: str, user_message: str) -> str:
        url = f"{self.cfg['base_url']}/chat/completions"
        headers = {
            "Authorization": f"Bearer {self.cfg['api_key']}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self.cfg["model"],
            "temperature": TEMPERATURE,
            "max_tokens": MAX_TOKENS,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_message},
            ],
        }
        resp = requests.post(url, headers=headers, json=payload, timeout=120)
        resp.raise_for_status()
        data = resp.json()
        return data["choices"][0]["message"]["content"]

    # ──────────────────────────────────────────
    # Anthropic (Claude)
    # ──────────────────────────────────────────
    def _call_anthropic(self, system_prompt: str, user_message: str) -> str:
        url = f"{self.cfg['base_url']}/messages"
        headers = {
            "x-api-key": self.cfg["api_key"],
            "anthropic-version": "2023-06-01",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self.cfg["model"],
            "max_tokens": MAX_TOKENS,
            "system": system_prompt,
            "messages": [
                {"role": "user", "content": user_message},
            ],
        }
        resp = requests.post(url, headers=headers, json=payload, timeout=120)
        resp.raise_for_status()
        data = resp.json()
        return data["content"][0]["text"]
